### ISSUE TITLE
1.7.3 가장 먼저 할 일: 데이터 살펴보기

### ISSUE THREAD

**Issue by denishong** [rickiepark/intro_ml_with_python_2nd_revised#1]
아래 에러 해결 방법 좀 가이드 부탁드립니다
Visual studio code에서 실행했을 때 아래 에러가 발생하고 google colab에서 실행하면 문제가 없이 잘 실행되네요.
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[32], line 7
      4 iris_dataframe
      5 # 데이터프레임을 사용해 y_train에 따라 색으로 구분된 산점도 행렬을 만듭니다.
      6 pd.plotting.scatter_matrix(iris_dataframe, c=y_train, figsize=(15, 15), marker='o',
----> 7                            hist_kwds={'bins': 20}, s=60, alpha=.8, cmap=mglearn.cm3)
      8 plt.show() # 책에는 없음

NameError: name 'mglearn' is not defined

위 에러가 발생하기 전에 아래에서 부터 에러가 발생하고 있었네요.
VSC 세팅에 뭔가 문제가 있어 보입니다. 코드 자체는 문제가 없어 보입니다.
![image](https://user-images.githubusercontent.com/25605767/222037475-59787eb3-176a-4e70-87ba-789737830023.png)

**Comment by rickiepark** [comment]
안녕하세요. 깃허브에서 mglearn 폴더를 작업 디렉토리에 복사했는지 확인해 주세요. 만약 IDE 환경에 관한 문제라면 제가 도움을 드리기 어렵습니다. 감사합니다.
